### ISSUE TITLE
Add more of a descriptive 'About' to the github repo

### ISSUE THREAD

**Issue by dorchard** [GO-SHIP-Oceanography/station_bathymetry#6]
This repo has a really nice README.md, but the summary 'About' message in GitHub is a bit short / mysterious. It would be useful for 'About' to be a bit more clear what the package is for.  What is a station exactly? In what context might people want to use/re-use this?

**Comment by jatkinson1000** [comment]
Thanks @dorchard 
@lcimoli do you want to meet to look at this (and maybe some other codes) at some point this week? - should be a quick fix.
I'll be around DAMTP for the seminar today

**Comment by jatkinson1000** [comment]
Closing this as I have updated the 'About' with more info and tags.
Feel free to re-open if you feel it could be improved further.
