### ISSUE TITLE
[New Code]: plot_bottles_over_topography

### ISSUE THREAD

**Issue by ShuwenTan-PO** [GO-SHIP-Oceanography/station_bathymetry#8]
### What does this code do?
This code plots bottle depths over topography along a GO-SHIP transect. 
### Why is it useful to the GO-SHIP/oceanographic cruise community?
Bottles along a GO-SHIP transect must be arranged to cover most of the water bodies. Therefore, instead of sampling at "standard levels", GO-SHIP uses three sampling schema in rotation to stagger standard sampling depths for consecutive stations. Caution needs to be exercised when designing bottle depths near changing bathymetry or when encountering a faulty bottle that consistently fails at the same depth. Both cases may cause two adjacent stations to have samples at similar depths. Being able to visualize planned, fired (and misfired) bottles over topography will help decision-making in terms of schema rotation and bottom depth design to prevent such occurrences.
### What are your contact details (github usernames/institute pages/emails)?
If the code already exists in a personal git repository please also link that here.
Shuwen Tan (@ShuwenTan-PO, s.tan@uci.edu)
### Does the code have a software license attached to it?
[MIT License](https://mit-license.org/)
### Have you read the GO-SHIP [contribution guidelines](https://github.com/GO-SHIP-Oceanography/.github/blob/main/contributing.md)?
Yes!

**Comment by jatkinson1000** [comment]
Hi @ShuwenTan-PO Thanks for doing this, really excited to get on and add the code!

Please could you open the issue [here](https://github.com/GO-SHIP-Oceanography/.github/issues) on the bulk GO-SHIP Organisation repository rather on this station-bathymetry repo (we will give you your own repo for the new code).

I'll review the main guidelines to clarify this as well.

**Comment by ShuwenTan-PO** [comment]
Sounds good, a new issue is now opened on the bulk GO-SHIP repository. Thanks!

**Comment by jatkinson1000** [comment]
Excellent, thank you.
Closing this now and will progress the new one in due course.
