### ISSUE TITLE
No module named 'tqdm'

### ISSUE THREAD

**Issue by ShuwenTan-PO** [GO-SHIP-Oceanography/station_bathymetry#9]
I encountered an error when executing cell 6 in plot_bathymetry_at_station.ipynb. Might be missing library in the virtual environment.

**Comment by jatkinson1000** [comment]
Hi @ShuwenTan-PO Thanks for testing this out and letting us know!

I just updated the code to fix this, please could you do a git-pull and see if everything works OK now?

**Comment by ShuwenTan-PO** [comment]
The code works perfectly now, thank you!
